config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :categories
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  after_save :clear_cache
  validates :title, :description, :isbn, :price, presence: true
  validates :pages, numericality: { only_integer: true }
  validates :price, :quantity, numericality: { greater_than_or_equal_to: 0 }


  def clear_cache
    $redis.del 'books'
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 4, maximum: 50 }
  validates :description, presence: true, length: { minimum: 15, maximum: 400 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  include BookHelper
  before_action :set_book, except: [:index, :create, :new]
  def index
    @books = fetch_books
  end

  def show
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book has been created"
      redirect_to @book
    else
      flash[:error] = "Book has not been created"
      render :new
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      flash[:notice] = "Book has been updated"
      redirect_to @book
    else
      flash[:error] = "Book has not been updated"
      render :new
    end
  end

  def destroy
    @book.destroy
    flash[:notice] = "Book has been deleted"
    redirect_to books_path
  end

  private
  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :description, :isbn, :publisshed_at, :pages, :price, :quantity)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, except: [:index, :create, :new]
  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category has been created"
      redirect_to @category
    else
      flash[:error] = "Category has not been created"
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      flash[:notice] = "Category has been updated"
      redirect_to @category
    else
      flash[:error] = "Category has not been updated"
      render :new
    end
  end

  def destroy
    @category.destroy
    flash[:notice] = "Category has been deleted"
    redirect_to categories_path
  end

  private
  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :description)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
  def fetch_books
    books = $redis.get("books")
    if books.nil?
      books = Book.all.to_json
      $redis.set("books", books)
      $redis.expire("books", 60.minutes.to_i)
    end
    @books = JSON.load books
  end
end

app/views/books/_form.html.haml
= bootstrap_form_for @book do |f|
  = f.text_field :title
  = f.text_area :description
  = f.text_field :isbn
  = f.date_field :published_at
  = f.number_field :pages
  = f.number_field :price
  = f.number_field :quantity
  = f.submit 'Save'

app/views/books/edit.html.haml
%h1 edit

app/views/books/index.html.haml
%h1.text-center Books

%table#books-list.table.table-bordered.table-hover
  %thead
    %tr
      %td Title
      %td Description
      %td ISBN
      %td Published at
      %td Pages
      %td Price
      %td Quantity
  %tbody
    - @books.each do |book|
      %tr
        %td= book['title']
        %td= book['description']
        %td= book['isbn']
        %td= book['published_at']
        %td= book['pages']
        %td= book['price']
        %td= book['quantity']

= link_to "New book", new_book_path, class: "btn btn-info"

app/views/books/new.html.haml
%h1.text_center Add a new book
.row
  .col-md-6.col-md-offset-3
    = render 'form'

app/views/books/show.html.haml
%h1 show

app/views/categories/_form.html.haml
= bootstrap_form_for @category do |f|
  = f.text_field :name
  = f.text_area :description
  = f.submit 'Save', class: 'btn btn-success'

app/views/categories/edit.html.haml
%h1 edit

app/views/categories/index.html.haml
%h1.text-center Categories

%table#categories-list.table.table-bordered.table-hover
  %thead
    %tr
      %td Name
      %td Description
  %tbody
    - @categories.each do |category|
      %tr
        %td= category.name
        %td= category.description
= link_to 'New Category', new_category_path, class: 'btn btn-info'

app/views/categories/new.html.haml
%h1.text_center Add a new category
.row
  .col-md-6.col-md-offset-3
    = render 'form'

app/views/categories/show.html.haml
%h1 show

app/views/home/index.html.haml
%h1 home

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CachingData
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-default
      .container-fluid
        / Brand and toggle get grouped for better mobile display
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => "#"} Brand
        / Collect the nav links, forms, and other content for toggling
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li.active
              %a{:href => "#"}
                Link
                %span.sr-only (current)
            %li
              =link_to "Books", books_path
            %li
              =link_to "Categories", categories_path
            %li.dropdown
              %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                dropdown
                %span.caret
              %ul.dropdown-menu
                %li
                %li
                  %a{:href => "#"} Another action
                %li
                  %a{:href => "#"} Something else here
                %li.divider{:role => "separator"}
                %li
                  %a{:href => "#"} Separated link
                %li.divider{:role => "separator"}
                %li
                  %a{:href => "#"} One more separated link
    .row
      .col-md-10.col-md-offset-1
        - flash.each do |name, msg|
          .alert.alert-succes
            %a{href: '#', class:'close', 'data-dismiss': 'alert'}
              &#215;
            = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

        = yield